import { InventoryItem } from './types'

export const inventoryData: InventoryItem[] = [
  {
    id: '1',
    ralCode: '1000',
    color: '#C9C490',
    brand: 'Teknos',
    productCode: 'PC8052',
    status: 'LAAG',
    currentStock: 8,
    maxStock: 183,
    minStock: 20,
    location: 'A1-01',
    lastUpdated: '27-6-2025',
    unit: 'kg',
    supplier: 'Teknos Nederland BV',
    weight: 25,
    costPerUnit: 12.50,
    description: 'Geelbeige poedercoating voor buitentoepassingen',
    transactions: [
      {
        id: 't1',
        date: '27-6-2025',
        type: 'OUT',
        quantity: 20,
        unit: 'kg',
        user: 'Jan Janssen',
        description: 'Verbruik voor project ABC123',
        reference: 'WO-2025-0156'
      },
      {
        id: 't2',
        date: '20-6-2025',
        type: 'IN',
        quantity: 50,
        unit: 'kg',
        user: 'Piet Peters',
        description: 'Nieuwe levering',
        reference: 'PO-2025-0089'
      }
    ]
  },
  {
    id: '2',
    ralCode: '1001',
    color: '#D0B084',
    brand: 'PPG',
    productCode: 'PC8893',
    status: 'GEM',
    currentStock: 133,
    maxStock: 279,
    minStock: 50,
    location: 'A2-01',
    lastUpdated: '22-6-2025',
    unit: 'kg',
    supplier: 'PPG Industries',
    weight: 25,
    costPerUnit: 14.75,
    description: 'Beige poedercoating voor industriële toepassingen',
    transactions: [
      {
        id: 't3',
        date: '22-6-2025',
        type: 'OUT',
        quantity: 15,
        unit: 'kg',
        user: 'Marie Jansen',
        description: 'Productie order 456',
        reference: 'WO-2025-0157'
      }
    ]
  },
  {
    id: '3',
    ralCode: '2000',
    color: '#ED760E',
    brand: 'Hempel',
    productCode: 'PC7823',
    status: 'GEM',
    currentStock: 253,
    maxStock: 280,
    minStock: 50,
    location: 'A1-01',
    lastUpdated: '13-7-2025',
    unit: 'kg',
    supplier: 'Hempel Netherlands',
    weight: 25,
    costPerUnit: 15.75,
    description: 'Oranje poedercoating voor industriële toepassingen',
    transactions: []
  },
  {
    id: '4',
    ralCode: '3000',
    color: '#AF2B1E',
    brand: 'PPG',
    productCode: 'PC7779',
    status: 'LAAG',
    currentStock: 183,
    maxStock: 204,
    minStock: 40,
    location: 'B1-01',
    lastUpdated: '17-6-2025',
    unit: 'kg',
    supplier: 'PPG Industries',
    weight: 20,
    costPerUnit: 18.25,
    description: 'Vuurrood poedercoating voor decoratieve toepassingen',
    transactions: []
  },
  {
    id: '5',
    ralCode: '5000',
    color: '#354D73',
    brand: 'Jotun',
    productCode: 'PC1677',
    status: 'GEM',
    currentStock: 24,
    maxStock: 306,
    minStock: 60,
    location: 'B1-02',
    lastUpdated: '21-6-2025',
    unit: 'kg',
    supplier: 'Jotun Nederland',
    weight: 25,
    costPerUnit: 16.50,
    description: 'Ultramarijn blauw poedercoating',
    transactions: []
  },
  {
    id: '6',
    ralCode: '6000',
    color: '#316650',
    brand: 'AkzoNobel',
    productCode: 'PC7493',
    status: 'GEM',
    currentStock: 332,
    maxStock: 363,
    minStock: 70,
    location: 'A1-01',
    lastUpdated: '18-6-2025',
    unit: 'kg',
    supplier: 'AkzoNobel Nederland',
    weight: 25,
    costPerUnit: 17.25,
    description: 'Patina groen poedercoating',
    transactions: []
  },
  {
    id: '7',
    ralCode: '7000',
    color: '#78858B',
    brand: 'Teknos',
    productCode: 'PC0458',
    status: 'GEM',
    currentStock: 54,
    maxStock: 256,
    minStock: 50,
    location: 'A2-01',
    lastUpdated: '10-7-2025',
    unit: 'kg',
    supplier: 'Teknos Nederland BV',
    weight: 25,
    costPerUnit: 13.75,
    description: 'Eekhoorn grijs poedercoating',
    transactions: []
  },
  {
    id: '8',
    ralCode: '7016',
    color: '#2F3A3D',
    brand: 'Hempel',
    productCode: 'PC9508',
    status: 'LAAG',
    currentStock: 322,
    maxStock: 362,
    minStock: 70,
    location: 'C1-01',
    lastUpdated: '10-7-2025',
    unit: 'kg',
    supplier: 'Hempel Netherlands',
    weight: 25,
    costPerUnit: 14.25,
    description: 'Antraciet grijs poedercoating',
    transactions: []
  },
  {
    id: '9',
    ralCode: '7035',
    color: '#D7D7D7',
    brand: 'Hempel',
    productCode: 'PC3159',
    status: 'LAAG',
    currentStock: 127,
    maxStock: 222,
    minStock: 45,
    location: 'A1-02',
    lastUpdated: '28-6-2025',
    unit: 'kg',
    supplier: 'Hempel Netherlands',
    weight: 20,
    costPerUnit: 12.75,
    description: 'Lichtgrijs poedercoating',
    transactions: []
  },
  {
    id: '10',
    ralCode: '9001',
    color: '#F4F4F4',
    brand: 'Jotun',
    productCode: 'PC7043',
    status: 'OK',
    currentStock: 274,
    maxStock: 479,
    minStock: 95,
    location: 'A2-01',
    lastUpdated: '16-6-2025',
    unit: 'kg',
    supplier: 'Jotun Nederland',
    weight: 25,
    costPerUnit: 11.50,
    description: 'Creme wit poedercoating',
    transactions: []
  }
]